### ISSUE TITLE
Sample to Get Access Token without public URL

### ISSUE THREAD

**Issue by RascoApps** [haseebmukhtar/AdobeSign.Net#2]
I have been searching for a good pattern to follow to get the access token for a Server side app that basically runs on a schedule?

Any ideas?  I have been trying to follow the documentation from Adobe you have at the end of the readme, but I have not had any luck.

**Comment by haseebmukhtar** [comment]
Hi,
I am using windows application and opening a browser with-in application for user login to get access token.

I think we need to get a first access token from User Interface (Browser component) because user have to allow different authorization access (like allow send file, allow read etc), but once we get a access token we can use a refresh token to get a new access token with out user interface or user login.

**On AdobeSign Api documentation it says;**

_At any point in the future the client can use the Refresh Token to receive an updated Access Token.

The client makes an HTTP POST to the /oauth/refresh endpoint (using the api_access_point retrieved in the authorization request step) with the following parameters:_

I have not tried the refresh token yet but going to have a look,

Thanks

**Comment by haseebmukhtar** [comment]
Please have a look at 
https://secure.na1.echosign.com/public/static/oauthDoc.jsp#refreshRequest

You need to get a access token first time using a user interface (may be web browser component), once you get a access token, you also get refresh token with it.
Then when your access token is expired you can use a refresh token to regenerate a new access token (with out any user interface, your server side scheduler can keep regenerating new access tokens on expiry)
